# Generated by Django 5.0.4 on 2024-04-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_birthday_user_currency_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="superhost",
            field=models.BooleanField(default=False),
        ),
    ]
