# Generated by Django 5.0.4 on 2024-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_email_secret_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOGIN_EMAIL", "Login Email"),
                    ("LOGIN_GITHUB", "Login Github"),
                    ("LOGIN_KAKAO", "Login Kakao"),
                ],
                default="LOGIN_EMAIL",
                max_length=20,
                null=True,
            ),
        ),
    ]
